language: python
python: 3.4
cache:
  directories:
    - $HOME/.pip-cache
env:
  - TOXENV=flake8
  - TOXENV=py26-py
  - TOXENV=py26-cy
  - TOXENV=py27-py
  - TOXENV=py27-cy
  - TOXENV=py33-py
  - TOXENV=py33-cy
  - TOXENV=py34-py
  - TOXENV=py34-cy
  - TOXENV=pypy
before_install:
  - pip install --download-cache $HOME/.pip-cache --use-wheel --install-option="--no-cython-compile" cython
  - pip install --download-cache $HOME/.pip-cache tox
install:
  - make build_ext
script:
  - tox -v
